version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: quizzez_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/data/postgres

  db-test:
    image: postgres
    environment:
      POSTGRES_DB: quizzez_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
